### ISSUE TITLE
(JAVA-W1004) Methods must not be empty

### ISSUE THREAD

**Issue by egeakman** [Scorpions-Robotics/Command-Based-2022#4]
## Description
This method is empty and does not appear to have any explanation regarding why. This may confuse future readers of this code. Additionally, such code produces needless, avoidable clutter.

## Occurrences
There are 19 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Scorpions-Robotics/Command-Based-2022/issue/JAVA-W1004/occurrences/](https://deepsource.io/gh/Scorpions-Robotics/Command-Based-2022/issue/JAVA-W1004/occurrences/)

**Comment by Ardasak** [comment]
I know these empty methods don't look good, however, we haven't tried our code. So that means we might have to add new code lines. Herein, we better keep these methods because why would we define them again if we need them later? We'll optimize the code in the best way when we are done with trials. But thanks for informing us.
